server:
  port: 7071
  error:
    include-message: always
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

# datasource
#spring:
 # datasource:
  #  driverClassName: com.mysql.cj.jdbc.Driver
   # url: jdbc:mysql://localhost:3306/java_spring?useTimezone=true&serverTimezone=UTC
    #username: root
    #password: Ana2704Luiza.
    
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./data/ms-funcionario
    username: sa
    password:       
  # jpa
  #jpa:
   # database-platform: org.hibernate.dialect.MySQL5Dialect
    #hibernate:
     # ddl-auto: update
      #spring.jpa.defer-datasource-initializantion: true
      
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update       
      
  # h2
  h2:
   console:
      enabled: true
      path: /h2-console